# 넘파이(Numpy)
    - 파이썬을 활용한 데이터 분석에서 가장 기본이 되는 라이브러리
    - 넘파이로만으로도 많이 사용되지만, 판다스(pandas), 머신러닝 들 수많은 분야에서  
    기본적으로 사용되므로 파이썬 개발자의 필수 라이브러리이다.

[넘파이 공식 문서](https://numpy.org/)

### 1) 수학 수치연산(numerical python)
    - 합, 평균, 행렬연산 등이 가능하다
### 2) 기본 타입
    - ndarray (n-dimenstional array) 다차원 배열의 표현
### 3) 파이썬 list가 있음에도 필요한 이유
    - 성능 : 성능적으로 훨씬 빠르다
    - 메모리 : 적은 메모리를 사용한다
    - 제공함수 : 선형대수, 통계관련 여러 수치 함수를 제공한다
    - 그 외 수 많은 모듈에서 numpy 함수명과 기능을 그대로 사용 가능하다

<img src="https://media.licdn.com/dms/image/v2/C5112AQHb27esqXVOjg/article-cover_image-shrink_600_2000/article-cover_image-shrink_600_2000/0/1579022691240?e=2147483647&v=beta&t=olCUsjnPDaaRqRj2Da7S0Hl5kEJxu7v11H1GSir50mc" width="800"/>

<img src="https://media.licdn.com/dms/image/v2/D4E22AQFKQ93ywmSGsg/feedshare-shrink_800/B4EZ.vxZJAHoAg-/0/1785360388974?e=2147483647&v=beta&t=qutjb0gyTs5FKZTWL_mxm1Xd_q22lPtZFuOiM5EAb5U" width="800"/>

파이썬과 다점 ->  타입을 강제로 승격 시킨다는 것 / 값을 가져왔을때 타입이 다르다는것 

In [1]:
import numpy as np 

In [5]:
arr1 = np.ndarray([1,2,3])

print(arr1)
print(type(arr1))

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [8.45596650e-307 1.89146896e-307 7.56571288e-307]]]
<class 'numpy.ndarray'>


In [7]:
arr1 = np.array([1,2,3])

print(arr1)
print(type(arr1))  # 콤마가 없지만 값은 나누어져 있음

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
arr2 = np.array([1,2,3])

arr2

array([1, 2, 3])

In [10]:
# 하나의 타입으로만 정의할 수 있다.
arr2 = np.array([      1,2,3.0])

print(arr2)
print([1,2,3.0])


[1. 2. 3.]
[1, 2, 3.0]


In [12]:
# 넘파이의 타입 강제 승격: 전부 문자열로 출력-> 이들을 하나로 정의할 수 있는 것이 문자열 밖에 없음
arr3 = np.array([1,2,False,"홍길동", 12.5])

print(arr3)

['1' '2' 'False' '홍길동' '12.5']


In [16]:
arr3 = np.array([i + 1 for i in range(10)])

print(arr3)
print("---------")
arr3

[ 1  2  3  4  5  6  7  8  9 10]
---------


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## ndarry의 인덱싱

In [22]:
print(arr3[1])
print(type(arr3[1]))
print(int(arr3[1]))  # 강제형변환

print("----------")
print(2)
print(type(2))

2
<class 'numpy.int64'>
2
----------
2
<class 'int'>


## ndarray의 슬라이싱

In [27]:
print(arr3) 
print(arr3[2:5])
print(arr3[::2]) 

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5]
[1 3 5 7 9]


### shape
    - numpy에서는 해당 array의 크기를 알 수 있다. shape를 확인함으로서, 몇 개의 데이터가 있는지 몇 차원으로 존재하는지 확인할 수 있다.
    - arr.shape의 결과는 튜플로 (행, 열)로 행만 존재하면 1차원, 행렬이 존재하면 2차원으로 차수를 알 수 있다. 또한 행*렬을 곱하면 크기도 확인할 수 있다.

In [31]:
print(arr3)
print(arr3.shape)


#(10,)
#1차원, 행의 10개 데이터

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [32]:
arr4 = np.array([2])
arr4

array([2])

In [34]:
# 2차원 스칼라 

print(arr4)
print(arr4.shape)

[2]
(1,)


In [36]:
arr5 = np.array([1,2,3],[4,5,6])

print(arr5)
print(arr5.shape)
#2행 3열 (2차원)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [35]:
arr6 = np.array([[1,2,3],[4,5,6]])


print(arr6)
print(arr6.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
print(arr6.shape)

#텐서
#2행3열

In [39]:
arr7 = np.array([
        [
            [10, 20, 30, 40],
            [50, 60, 70, 80],
            [90, 100, 110, 120],
        ],
        [
            [100, 200, 300, 400],
            [500, 600, 700, 800],
            [900, 1000, 1100, 1200],
        ],
    ])

print(arr7)
print(arr7.shape)
#3차원텐서

[[[  10   20   30   40]
  [  50   60   70   80]
  [  90  100  110  120]]

 [[ 100  200  300  400]
  [ 500  600  700  800]
  [ 900 1000 1100 1200]]]
(2, 3, 4)


In [40]:
arr7.ndim

3

In [41]:
# 데이터의 개수
print(arr7.size)

24
