# 넘파이(Numpy)
    - 파이썬을 활용한 데이터 분석에서 가장 기본이 되는 라이브러리
    - 넘파이로만으로도 많이 사용되지만, 판다스(pandas), 머신러닝 들 수많은 분야에서  
    기본적으로 사용되므로 파이썬 개발자의 필수 라이브러리이다.

[넘파이 공식 문서](https://numpy.org/)

### 1) 수학 수치연산(numerical python)
    - 합, 평균, 행렬연산 등이 가능하다
### 2) 기본 타입
    - ndarray (n-dimenstional array) 다차원 배열의 표현
### 3) 파이썬 list가 있음에도 필요한 이유
    - 성능 : 성능적으로 훨씬 빠르다
    - 메모리 : 적은 메모리를 사용한다
    - 제공함수 : 선형대수, 통계관련 여러 수치 함수를 제공한다
    - 그 외 수 많은 모듈에서 numpy 함수명과 기능을 그대로 사용 가능하다

<img src="https://media.licdn.com/dms/image/v2/C5112AQHb27esqXVOjg/article-cover_image-shrink_600_2000/article-cover_image-shrink_600_2000/0/1579022691240?e=2147483647&v=beta&t=olCUsjnPDaaRqRj2Da7S0Hl5kEJxu7v11H1GSir50mc" width="800"/>

<img src="https://media.licdn.com/dms/image/v2/D4E22AQFKQ93ywmSGsg/feedshare-shrink_800/B4EZ.vxZJAHoAg-/0/1785360388974?e=2147483647&v=beta&t=qutjb0gyTs5FKZTWL_mxm1Xd_q22lPtZFuOiM5EAb5U" width="800"/>

파이썬과 다점 ->  타입을 강제로 승격 시킨다는 것 / 값을 가져왔을때 타입이 다르다는것 

In [21]:
import numpy as np 

In [5]:
arr1 = np.ndarray([1,2,3])

print(arr1)
print(type(arr1))

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [8.45596650e-307 1.89146896e-307 7.56571288e-307]]]
<class 'numpy.ndarray'>


In [7]:
arr1 = np.array([1,2,3])

print(arr1)
print(type(arr1))  # 콤마가 없지만 값은 나누어져 있음

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
arr2 = np.array([1,2,3])

arr2

array([1, 2, 3])

In [10]:
# 하나의 타입으로만 정의할 수 있다.
arr2 = np.array([      1,2,3.0])

print(arr2)
print([1,2,3.0])


[1. 2. 3.]
[1, 2, 3.0]


In [12]:
# 넘파이의 타입 강제 승격: 전부 문자열로 출력-> 이들을 하나로 정의할 수 있는 것이 문자열 밖에 없음
arr3 = np.array([1,2,False,"홍길동", 12.5])

print(arr3)

['1' '2' 'False' '홍길동' '12.5']


In [16]:
arr3 = np.array([i + 1 for i in range(10)])

print(arr3)
print("---------")
arr3

[ 1  2  3  4  5  6  7  8  9 10]
---------


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## ndarry의 인덱싱

In [22]:
print(arr3[1])
print(type(arr3[1]))
print(int(arr3[1]))  # 강제형변환

print("----------")
print(2)
print(type(2))

2
<class 'numpy.int64'>
2
----------
2
<class 'int'>


## ndarray의 슬라이싱

In [27]:
print(arr3) 
print(arr3[2:5])
print(arr3[::2]) 

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5]
[1 3 5 7 9]


### shape
    - numpy에서는 해당 array의 크기를 알 수 있다. shape를 확인함으로서, 몇 개의 데이터가 있는지 몇 차원으로 존재하는지 확인할 수 있다.
    - arr.shape의 결과는 튜플로 (행, 열)로 행만 존재하면 1차원, 행렬이 존재하면 2차원으로 차수를 알 수 있다. 또한 행*렬을 곱하면 크기도 확인할 수 있다.

In [31]:
print(arr3)
print(arr3.shape)


#(10,)
#1차원, 행의 10개 데이터

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [32]:
arr4 = np.array([2])
arr4

array([2])

In [34]:
# 2차원 스칼라 

print(arr4)
print(arr4.shape)

[2]
(1,)


In [36]:
arr5 = np.array([1,2,3],[4,5,6])

print(arr5)
print(arr5.shape)
#2행 3열 (2차원)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [35]:
arr6 = np.array([[1,2,3],[4,5,6]])


print(arr6)
print(arr6.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
print(arr6.shape)

#텐서
#2행3열

In [39]:
arr7 = np.array([
        [
            [10, 20, 30, 40],
            [50, 60, 70, 80],
            [90, 100, 110, 120],
        ],
        [
            [100, 200, 300, 400],
            [500, 600, 700, 800],
            [900, 1000, 1100, 1200],
        ],
    ])

print(arr7)
print(arr7.shape)
#3차원텐서

[[[  10   20   30   40]
  [  50   60   70   80]
  [  90  100  110  120]]

 [[ 100  200  300  400]
  [ 500  600  700  800]
  [ 900 1000 1100 1200]]]
(2, 3, 4)


In [40]:
arr7.ndim

3

In [41]:
# 데이터의 개수
print(arr7.size)

24


## np.arange()

In [3]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.array(10)

array(10)

In [5]:
list(range(5, 10))

[5, 6, 7, 8, 9]

In [6]:
list(range(5, 10, 2))

[5, 7, 9]

In [7]:
np.arange(1, 7)

array([1, 2, 3, 4, 5, 6])

In [8]:
np.arange(1,7,2)

array([1, 3, 5])

In [10]:
arr1 = np.arange(10)

print(arr1[6])
print(type(arr1[6]))

6
<class 'numpy.int64'>


In [11]:
arr2 = np.arange(10, dtype=np.uint8)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

## 넘파이의 자료형
- int: 부호가 있는 정수(8, 16, 32, 64)
- uint: 부호가 없는 정수(8, 16, 32, 64)
- float: 실수(16, 32, 64, 128)
- complex: x복소수(64, 128, 256)
- bool: 불리언(8)
- string_: 문자열(8)
- object: 오브젝트(64)

## astype(타입)
- 기존의 배열을 복사하고 타입을 변경하고 싶을 떄

In [13]:
arr2 = np.arange(10)

print(arr2.dtype)


int64


## np.reshaple()

In [15]:
arr3 = np.arange(12)

print(arr3.ndim)
print(arr3.shape)

1
(12,)


In [ ]:
# 행과 열의 개수가 다르면 쪼개도 합쳐질 수 없음, 행과열의 데이터들을 
# 행과열이 곱해지는 연산을 했을때 네모로 되는것고  ㅏ 가타? 백터곱말하는겅ㅇ가 ?
# 6 X 2 = 12 -> 6행 2열 -> reshape(6,2)

In [25]:
arr3.reshape(2,1,2,3)  # 차원텐서

array([[[[ 0,  1,  2],
         [ 3,  4,  5]]],


       [[[ 6,  7,  8],
         [ 9, 10, 11]]]])

1,1,4,3 -> 4행 3열 데이터가 백터로 하나 존재하고 또 하나 차원으로 존재

In [27]:
# reshape의 개수와 데이터의 개수가 맞지 않으면 오류
arr3.reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
arr4 = np.arange(24)
arr4

## np.ones(), np.zeros()
- ndarray의 초기값을 0또는 1로 설정하기 위한 메서드

In [28]:
arr5 = np.ones(8)
print(arr5)
print(type(arr5[0]))

[1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.float64'>


In [32]:
arr6 = np.zeros(64, dtype=np.int64)
print(arr6)
print(type(arr6[0]))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
<class 'numpy.int64'>


In [35]:
arr6.reshape(4, 16) #(행, 열) -> 16행 4열 (2차원인 상태)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## np.random
- rand: 0 ~ 1 사이의 균일 분포
- randn: 정규분포
- randint: 균일 분포 정규 난수

<img src="https://thebook.io/img/080263/218.jpg" />

In [36]:
np.random.randn(5)

array([ 0.66974111,  0.28362766, -0.30871237, -1.27940912,  0.23820944])

In [37]:
# 0 ~ 4 사이의 난수
np.random.randint(5)

0

In [38]:
np.random.randint(50,101)

55

In [39]:
np.random.randint(0,100)

12

In [40]:
np.random.randint(1, 46, (2,3))

array([[37, 22, 15],
       [17, 41, 31]], dtype=int32)

## seed()
- 난수를 예측가능하도록 만들며, 실행할 떄마다 동일한 난수를 발생시켜
   코드의 재현성, 특정 알고리즘의 결과를 재현하게 만든다.
   또한 해당 알고리즘의 결과의 오류를 추적하기 위해 사용한다.

In [41]:
np.random.seed(4885)

np.random.randint(10, size=(2,5))

array([[9, 1, 0, 3, 4],
       [8, 7, 4, 7, 6]], dtype=int32)

In [43]:
np.random.seed(4885)

# 0 ~ 1 까지의 균등분포
np.random.rand(2, 5)

array([[0.21350835, 0.56504926, 0.7597468 , 0.05666448, 0.6753598 ],
       [0.36138766, 0.01299493, 0.04721084, 0.26603997, 0.8042786 ]])

## unique 
- ndarry의 중복값을 제거해주는 함수
- 엑스칼리버..


In [44]:
np.unique([11,11,11,14,15])

array([11, 14, 15])

In [ ]:
arr7.ravel()

In [ ]:
# C:roq 방향
arr7.ravel(order="C")

In [45]:
arr7.ravel(order="F")

NameError: name 'arr7' is not defined

## np.flatten()
- copy를 생성하고 원본 배열을 변경하지 않는 복사본을 반환한다

In [46]:
arr7 = np.arange(24).reshape(2, 12)

print(arr7)
print(arr7.flatten())

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [47]:
arr7 = np.arange(24).reshape(2, 3, 4)

print(arr7)
print(arr7.flatten())

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [49]:
# -1: 차원유추
arr8 = np.arange(120).reshape(2, -1, 12)
arr8

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]])

## 차원 확장
- np.expand_dims()
- axis로 지정된 축을확장 시키는 메서드

In [50]:
arr8 = np.arange(10)
print(arr8.shape)

(10,)


In [55]:
arr9 = np.expand_dims(arr8, axis=8)

print(arr9)
print(arr9.shape)

AxisError: axis 8 is out of bounds for array of dimension 2

## 차원축소
- squeez(), np.squeez()

In [ ]:
print(arr9.squeez())

## 전치행렬(transpose)

In [56]:
# 2,3 -> 3,2
arr1 = np.arange(15).reshape(3,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
np.transpose(arr1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [60]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [61]:
arr2 = np.arange(12).reshape(2,6)
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [62]:
print(arr2.T)

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


In [64]:
print(arr2.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## array간의 연산

In [66]:
[1,2,3]+[1,2,3]  # +: 시퀀스 연산자 (더하기 )

[1, 2, 3, 1, 2, 3]

In [67]:
# 리스트 간의 연산

arr1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
arr1 + [10]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
arr1 + [[10]]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
# 2차원 + 2차원
# 3차원

arr1+ [[[10]]]

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

## 브로드캐스팅
- 다른 크기의 배열들 간에도 자동으로 연산해주는 Numpy의 강력한 기능

## 브로드캐스팅의 특징
    - 기본적으로는 shape와 같은 두 ndarray에 대한 연산은 각 원소별로 진행한다
    - 다른 shape를 갖는 array 간의 연산의 경우 브로드 캐스팅(shape를 맞춤) 후 진행한다

<img width=500 src='https://www.astroml.org/_images/fig_broadcast_visual_1.png' />

In [74]:
arr1 = np.arange(12).reshape(4,3)
arr1

print(arr1.shape)

(4, 3)


In [75]:
arr2 = np.arange(3)

print(arr2)
print(arr2.shape)

[0 1 2]
(3,)


In [77]:
"""
  차원에 1이 존재하는 경우 확장이 가능하다.
    6 x 1 x 5
        7 x 3

    6 x 7 x 5

"""

None

In [78]:
arr1 = np.arange(100,104)
print(arr1)

[100 101 102 103]


In [79]:
# (4,3)
arr2 = np.arange(12).reshape

<img src="https://numpy.org/doc/stable/_images/broadcasting_3.png" />

In [93]:
# (2,3),(3,2)

arr3 = np.arange(6).reshape(2,3)

arr4 = np.arange(100, 106).reshape(3,2)


print(arr3)
print(arr4)


[[0 1 2]
 [3 4 5]]
[[100 101]
 [102 103]
 [104 105]]


#### 열의 개수가 같아야, 계산이 가능하다

In [94]:
arr3 + arr4

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

#### 아니면 계산이 가능하도록 차원을 바꾸주면 된다 

In [95]:
arr3.T + arr4

array([[100, 104],
       [103, 107],
       [106, 110]])

## 차원축(axis)
- 1차원 array라면 각 차원에 대한 axis 값은 0
- 2차원 array라면 각 차원에 대한 axis 값은 0, 1
- 3차원 array라면 각 차원에 대한 axis 값은 0, 1, 2

In [96]:
arr1 = np.arange(15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [97]:
np.sum(arr1, axis=0)

np.int64(105)

In [98]:
arr1 = np.arange(15).reshape(3,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [101]:
np.sum(arr1, axis=0)

array([15, 18, 21, 24, 27])

In [102]:
np.sum(arr1, axis=1)

array([10, 35, 60])

In [106]:
arr2 = np.arange(24).reshape(2,3,4)  # 3차원 데이터
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [107]:
np.sum(arr2, axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

## ※argmax() 중요!!!!!!!!!!!!!!!!!!!!!!!!!!!!



- 최대값의 인덱스

In [108]:
arr3 = np.arange(5, 10)
print(arr3)
print(arr3[arr3.argmax()])

[5 6 7 8 9]
9


In [113]:
np.random.seed(918)

arr4 = np.random.randint(10, size=(1,6)).flatten()

print(arr4.argmax())  # 가장 큰 값의 인덱스
print(arr4.argmin())  # 가장 작은 값의 인덱스
print(arr4.max())  # 가장 큰 값
print(arr4.min)  # 가장 작은 값

print(np.argmax(arr4))

0
4
9
<built-in method min of numpy.ndarray object at 0x000002C72B63A490>
0


In [114]:
arr5 = np.random.randint(10, size=(3,6))
arr5

array([[0, 6, 5, 0, 8, 5],
       [3, 4, 6, 8, 1, 8],
       [4, 8, 2, 3, 7, 7]], dtype=int32)

In [117]:
print(arr5.argmax(axis=0))  # 접근 방법이 어디를 접근하는지에 따라서 달라질 수 있다 

[2 2 1 1 0 1]


In [116]:
print(arr5.argmax(axis=1))

[4 3 1]


In [118]:
print(arr5.min(axis=0))

[0 4 2 0 1 5]


## boolean selection, boolean indexing
- array 인덱싱 시, boll 타입의 조건에 맞는 list를 전달하여 조건식을 만족하는 True의 결과물만 필터링한다.

In [119]:
arr4 = np.random.randint(1, 100, size=20)
print(arr4)

[39 22 55 93 43 16 97 45 71 33 71 46 44 67 23 84 26 42 31 96]


In [123]:
arr4 + 5

array([ 44,  27,  60,  98,  48,  21, 102,  50,  76,  38,  76,  51,  49,
        72,  28,  89,  31,  47,  36, 101], dtype=int32)

In [124]:
arr4 - 5

array([34, 17, 50, 88, 38, 11, 92, 40, 66, 28, 66, 41, 39, 62, 18, 79, 21,
       37, 26, 91], dtype=int32)

In [125]:
arr4 / 5

array([ 7.8,  4.4, 11. , 18.6,  8.6,  3.2, 19.4,  9. , 14.2,  6.6, 14.2,
        9.2,  8.8, 13.4,  4.6, 16.8,  5.2,  8.4,  6.2, 19.2])

In [129]:
arr4 % 5

array([4, 2, 0, 3, 3, 1, 2, 0, 1, 3, 1, 1, 4, 2, 3, 4, 1, 2, 1, 1],
      dtype=int32)

In [132]:
 # 짝수 마스크
even_mask = arr4 % 2 == 0
arr4[even_mask]

array([22, 16, 46, 44, 84, 26, 42, 96], dtype=int32)

In [ ]:
is_bound = arr4 > 30
arr4

## 다중조건식
- &: and 조건식
- | :or 조건식

In [138]:
# 홀수이면서 50보다 작은 값
# and:

np.random.seed(2026)
arr5 = np.random.randint(100, size=15)
arr5

array([ 1,  6, 26, 56, 77, 77, 29, 28, 51, 69, 76, 28,  2, 54, 77],
      dtype=int32)

In [141]:
is_bound= arr5 % 2 == 1 & (arr5 < 50)
arr5[is_bound]

array([ 1, 56, 29, 76, 54], dtype=int32)

In [143]:
arr5[is_bound].astype(str)

array(['1', '56', '29', '76', '54'], dtype='<U11')